// <auto-generated />
namespace Werkverantwoording.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedtaskIDlistinsideofprogresstointlistfromstringlist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedtaskIDlistinsideofprogresstointlistfromstringlist));
        
        string IMigrationMetadata.Id
        {
            get { return "201506020854518_changed taskID list inside of progress to int list from string list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
