// <auto-generated />
namespace Werkverantwoording.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddednewmodelnamedDay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddednewmodelnamedDay));
        
        string IMigrationMetadata.Id
        {
            get { return "201506021053400_Added new model named Day"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
