// <auto-generated />
namespace Werkverantwoording.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedtaskiDinsideofprogressfrominttolist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedtaskiDinsideofprogressfrominttolist));
        
        string IMigrationMetadata.Id
        {
            get { return "201506020852060_changed taskiD inside of progress from int to list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
